name: geopattern_example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  geopattern_flutter:
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  crypto: ^3.0.3

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: false
