name: geopattern_flutter
description: Geometric patterns for flutter, based on geo_pattern ruby library.
version: 0.1.1
homepage: https://github.com/suyash/geopattern

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
